#!/bin/sh
VERSION="4.2"
LOCAL=$(cat /usr/share/somo/latest_monitor)
ONLINE=$(git ls-remote https://github.com/didiatworkz/screenly-ose-monitoring | head -1 | sed "s/\tHEAD//")
ACTION='\033[1;90m'
FOUND='\033[1;92m'
NOCOLOR='\033[0m'
ERROR='\033[0;31m'
PHPVERSION=$(php -v | head -n1 | grep -Po '(?<=PHP )([0-9]+.[0-9]+)')
IP=$(ip route get 8.8.8.8 | sed -n '/src/{s/.*src *\([^ ]*\).*/\1/p;q}')
if [ ! -e /home/pi/screenly/server.py ]
then
  PORT=""
else
  PORT=":9000"
fi

while [[ $# -gt 0 ]] ; do
    case $1 in
        -h|-\?|--help)
        tput setaf 172
        cat << "EOF"
                                    _
           ____                    | |
          / __ \__      _____  _ __| | __ ____
         / / _` \ \ /\ / / _ \| '__| |/ /|_  /
        | | (_| |\ V  V / (_) | |  |   <  / /
         \ \__,_| \_/\_/ \___/|_|  |_|\_\/___|
          \____/                www.atworkz.de

                Screenly OSE Monitoring (SOMO)
EOF
      tput sgr 0
      echo
			echo "Screenly OSE Monitoring is a web-based application that is simultaneously"
      echo "installed on a Screenly OSE Player or as standalone solution."
			echo "You can open the web-interface via the IP address \"$IP$PORT\"."
      echo
			echo "In addition, the monitoring offers an add-on that can be installed on other"
			echo "players to display the current online status of the player or some"
      echo "other system relevant information."
			echo
			echo "Options: "
			echo "  -v / --version    | Show current installed Version"
			echo "  -r / --restart    | Restart the nginx services"
			echo "  -c / --check      | Check all of all required files"
			echo "  -u / --update     | Update to the latest version"
      echo "  --reset-version   | Reset system version to initiate DB refresh"
			echo "  -d / --uninstall  | Uninstall Screenly OSE Monitoring"
      echo
      echo
            ;;
        -v|--version)
			echo "$VERSION"
			shift
            ;;
        -r|--restart)
			echo "Restart nginx service"
			sudo systemctl restart nginx
      echo "Restart php$PHPVERSION-fpm service"
			sudo systemctl restart php$PHPVERSION-fpm
            ;;
        --reset-version)
  		echo "Reset system version to 3.0"
  		echo "3.0" > /var/www/html/assets/tools/version_old.txt
          ;;
		    --init)
			echo "Set version..."
			cp -rf /var/www/html/assets/tools/version.txt /var/www/html/assets/tools/version_old.txt
			echo $VERSION > /var/www/html/assets/tools/version.txt
            ;;
        -c|--check)
      echo
			echo "Check file integrity..."
			sleep 2

      array=""
      array="${array} index.php"
      array="${array} _functions.php"
      array="${array} _public.php"
      array="${array} assets/php/actions.php"
      array="${array} assets/php/addon.php"
      array="${array} assets/php/curl.php"
      array="${array} assets/php/dashboard.php"
      array="${array} assets/php/database.php"
      array="${array} assets/php/datatable_lang.json.php"
      array="${array} assets/php/deviceInfo.php"
      array="${array} assets/php/discover.php"
      array="${array} assets/php/dropzone_lang.js.php"
      array="${array} assets/php/error_handler.php"
      array="${array} assets/php/firstStart.php"
      array="${array} assets/php/functions.php"
      array="${array} assets/php/groupmanagement.php"
      array="${array} assets/php/image.php"
      array="${array} assets/php/login.php"
      array="${array} assets/php/menu.php"
      array="${array} assets/php/multiuploader.php"
      array="${array} assets/php/player.php"
      array="${array} assets/php/runner.php"
      array="${array} assets/php/settings.php"
      array="${array} assets/php/ssh.class.php"
      array="${array} assets/php/translation.php"
      array="${array} assets/php/update.php"
      array="${array} assets/php/user.php"
      array="${array} assets/php/usermanagement.php"

      FAILCOUNTER=0
      for i in "${array[@]}"
      do
        echo
  		    echo -e ${ACTION}Check if "$i" exists
  		    echo -e ----------------------------------------------------${NOCOLOR}
  		    if [ ! -e "/var/www/html/monitor/$i" ]
  		    then
  		      echo -e ${ERROR}"$i not exists "${NOCOLOR}
            FAILCOUNTER=$[$FAILCOUNTER +1]
  		    else
  			    echo -e ${FOUND}"$i exists "${NOCOLOR}
  		    fi
  			echo
      done
      if [ "$FAILCOUNTER" -gt 0 ]; then
        echo
        echo ================================================================
        echo -e ${ERROR}"Several files are missing! - Please check "${NOCOLOR}
      else
        echo
        echo ================================================================
        echo -e ${FOUND}"All files were found "${NOCOLOR}
      fi
      echo
      echo
            ;;
        -u|--update)
			echo "Check for newer version..."
			if [ "$LOCAL" == "$ONLINE" ]
			then
			  echo -e "No Update available!"
		      echo
		      exit 0
			else
		      echo "Update available!"
			  read -p "Do you want to start the update? [y] (y/N)" -n 1 -r -s UPDATE_BEGIN
			  if [ "$UPDATE_BEGIN" != 'y' ]
			  then
				echo
				exit 0
			  fi
			  bash <(curl -sL https://raw.githubusercontent.com/didiatworkz/screenly-ose-monitoring/master/assets/tools/install_monitor.sh)
			fi
            ;;
        -d|--uninstall)
        echo
        echo
        echo
			  echo -e ${ERROR}"Uninstallation of Screenly OSE Monitoring "${NOCOLOR}
			  echo -e ${ERROR}"All data will be permanently removed! "${NOCOLOR}
        echo
			  read -p "Do you want to uninstall SOMO? [Y] (Y/n)" -n 1 -r -s UNINSTALL_BEGIN
			  if [ "$UNINSTALL_BEGIN" == 'Y' ]
			  then
          echo
          echo
				  echo "Uninstallation started..."
          sleep 5
          echo
          echo
          echo "Remove /var/www/html/monitor"
          sudo rm -rf /var/www/html/monitor
          echo "Remove /usr/share/somo"
          sudo rm -rf /usr/share/somo
          echo "Remove /etc/nginx/sites-enabled/monitoring.conf"
          sudo rm -rf /etc/nginx/sites-enabled/monitoring.conf
          echo "Restart nginx service"
          sudo systemctl restart nginx
          echo "Remove /usr/bin/somo"
          sudo rm -rf /usr/bin/somo
          echo
          echo "Uninstallation complete..."
          echo
          echo "Thank you for using Screenly OSE Monitoring (SOMO)"
          echo "- didiatworkz"
          echo
          echo
          echo
				  exit 0
			  fi
        echo
			  exit 0
            ;;
		    --scriptupdate)
			if [ "$LOCAL" == "$ONLINE" ]
			then
		      exit 0
			else
		      echo true > /var/www/html/monitor/update.txt
			  exit 0
			fi
			echo Done!
            ;;
		*)
			echo "Invalid Option! - Please enter --help for more commands"
            ;;
    esac
    shift
done
exit 0
