#!/bin/bash
VERSION="3.0"
LOCAL=$(cat /home/pi/.monitor/latest_monitor)
ONLINE=$(git ls-remote https://github.com/didiatworkz/screenly-ose-monitor | head -1 | sed "s/\tHEAD//")
ACTION='\033[1;90m'
FOUND='\033[1;92m'
NOCOLOR='\033[0m'
ERROR='\033[0;31m'

while [[ $# -gt 0 ]] ; do
    case $1 in
        -h|-\?|--help)
        cat << "EOF"
                                    _
           ____                    | |
          / __ \__      _____  _ __| | __ ____
         / / _` \ \ /\ / / _ \| '__| |/ /|_  /
        | | (_| |\ V  V / (_) | |  |   <  / /
         \ \__,_| \_/\_/ \___/|_|  |_|\_\/___|
          \____/                www.atworkz.de

                Screenly OSE Monitoring
EOF
      echo
			echo "Screenly OSE-Monitoring is an overview page for all Screenly OSE players."
			echo "You can open it via the IP address \"0.0.0.0:9000\" and manage all players in one place."
			echo "In addition, the monitoring offers an extension that can be installed on other"
			echo "players to always display the current display of the player."
			echo
			echo "Options: "
			echo "  --version | Show current installed Version"
			echo "  --restart | Restart the nginx Server"
			echo "  --check   | Check all of all required files"
			echo "  --update  | Update to the latest version"
            ;;
        -v|--version)
			echo "$VERSION"
			shift
            ;;
        --restart)
			echo "Restart nginx service"
			sudo systemctl restart nginx
      echo "Restart php7.3-fpm service"
			sudo sudo systemctl restart php7.3-fpm
            ;;
		--init)
			echo "Set version..."
			cp -rf /var/www/html/monitor/assets/tools/version.txt /var/www/html/monitor/assets/tools/version_old.txt
			echo $VERSION > /var/www/html/monitor/assets/tools/version.txt
            ;;
        --check)
			echo "Check Script..."
			sleep 2

      array=( index.php _functions.php assets/css/monitor.css assets/js/monitor.js assets/tools/key.php assets/tools/version.txt assets/php/actions.php assets/php/database.php assets/php/discover.php assets/php/image.php assets/php/menu.php assets/php/multiuploader.php assets/php/player.php assets/php/publicLink.php assets/php/update.php assets/php/user.php assets/php/usermanagement.php )
      for i in "${array[@]}"
      do
        echo
  		    echo -e ${ACTION}Check if "$i" exists
  		    echo -e =======================${NOCOLOR}
  		    if [ ! -e "/var/www/html/monitor/$i" ]
  		    then
  		      echo -e ${ERROR}"$i not exists "${NOCOLOR}
  		    else
  			  echo -e ${FOUND}"$i exists "${NOCOLOR}
  		    fi
  			echo
      	echo
      done
            ;;
        --update)
			echo "Check for newer version..."
			if [ "$LOCAL" == "$ONLINE" ]
			then
			  echo -e "No Update available!"
		      echo
		      exit 0
			else
		      echo "Update available!"
			  read -p "Do you want to start the update? [y] (y/N)" -n 1 -r -s UPDATE_BEGIN
			  if [ "$UPDATE_BEGIN" != 'y' ]
			  then
				echo
				exit 0
			  fi
			  bash <(curl -sL http://screenly-monitor.atworkz.de)
			fi
            ;;
		--scriptupdate)
			if [ "$LOCAL" == "$ONLINE" ]
			then
		      exit 0
			else
		      echo true > /var/www/html/monitor/update.txt
			  exit 0
			fi
			echo Done!
            ;;
		*)
			echo "Invalid Option! - Please enter --help for more commands"
            ;;
    esac
    shift
done
exit 0
